export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const GET_CONTACTS_LOADING = "GET_CONTACTS_LOADING";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_ERROR = "GET_CONTACTS_ERROR";

export const ADD_CONTACT_LOADING = "ADD_CONTACTS_LOADING";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACTS_SUCCESS";
export const ADD_CONTACT_ERROR = "ADD_CONTACTS_ERROR";
export const CLEAR_ADD_CONTACT = "CLEAR_ADD_CONTACT";

export const LOGOUT_USER = "LOGOUT_USER";

export const SEARCH_CONTACTS = "SEARCH_CONRACTS"

export const DELETE_CONTACT_LOADING = "DELETE_CONTACT_LOADING";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_ERROR = "DELETE_CONTACT_ERROR";


export const ADD_REMOVE_FROM_FAVORITE_LOADING = "ADD_REMOVE_FROM_FAVORITE_LOADING";
export const ADD_REMOVE_FROM_FAVORITE_SUCCESS = "ADD_REMOVE_FROM_FAVORITE_SUCCESS";
export const ADD_REMOVE_FROM_FAVORITE_ERROR ="ADD_REMOVE_FROM_FAVORITE_ERROR";

export const UPDATE_CONTACT_LOADING = "UPDATE_CONTACT_LOADING";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const UPDATE_CONTACT_ERROR = "UPDATE_CONTACT_ERROR";

export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_LOADING_SUCCESS = "PROFILE_LOADING_SUCCESS";
export const PROFILE_LOADING_ERROR = "PROFILE_LOADING_ERROR"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_ERROR = "UPDATE_PROFILE_ERROR";