export const {
    REACT_APP_FIREBASE_API_KEY,
    REACT_APP_AUTH_DOMAIN,
    REACT_APP_DATABASE_URL,
    REACT_APP_PROJECT_ID,
    REACT_APP_FIREBASE_STORAGE_BUCKET,
    REACT_APP_FIREBASE_MESSAGIN_ID,
    REACT_APP_FIREBASE_API_ID,
} = process.env;

export const FIREBASE_IMAGE_REF ="truly_contact_images"